In [1]:
#exercice2
import numpy as np
y=int(input("donner un nombre de ligne:"))
x=int(input("donner le nombre de la liste:"))
a=np.arange(x).reshape(y,y)
print(a)
A = np.trace(a) 
print(A)

donner un nombre de ligne:3
donner le nombre de la liste:9
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [2]:
#exercice1
from array import *
array_num = array('i', [1, 9,7,9,4,9,3,0,7])
print("array 2: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

array 2: array('i', [1, 9, 7, 9, 4, 9, 3, 0, 7])
Convert the said array to an ordinary list with the same items:
[1, 9, 7, 9, 4, 9, 3, 0, 7]


In [11]:
#exercice3
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=int(input("give a number"))
for i in a:
    for j in i:
        if j>b:
            
            print(j)
print(j)

give a number5
6
7
8
9
9


In [7]:
#exercice4
import numpy as np
a=np.random.randint(2,10,size=(2,2))
b=np.random.randint(2,10,size=(2,2))
print(a)
print(b)
c=a+b
print(c)

[[8 9]
 [4 5]]
[[4 8]
 [2 3]]
[[12 17]
 [ 6  8]]


In [2]:
#exercice5
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)



Original matrix:

[[0.87918454 0.88106147 0.26496716 0.37872033 0.63003494 0.77931982
  0.1252399  0.43772847 0.5185415  0.70952781]
 [0.75217001 0.76368838 0.81616747 0.01652243 0.16175963 0.66591595
  0.40942007 0.44282541 0.88204598 0.67861444]
 [0.82255223 0.91933259 0.94380683 0.09126073 0.46834886 0.19857531
  0.06676047 0.62961297 0.58588356 0.03482866]
 [0.13945077 0.59512765 0.12573385 0.94713225 0.90791876 0.91943179
  0.29478309 0.44385809 0.00528185 0.36868378]
 [0.34258148 0.28459682 0.4189874  0.43576682 0.74361091 0.08010477
  0.6749062  0.25107878 0.29336033 0.64743768]]

Subtract the mean of each row of the said matrix:

[[ 0.31875195  0.32062888 -0.29546544 -0.18171226  0.06960235  0.21888722
  -0.4351927  -0.12270413 -0.04189109  0.14909522]
 [ 0.19325704  0.20477541  0.2572545  -0.54239055 -0.39715335  0.10700298
  -0.1494929  -0.11608757  0.323133    0.11970146]
 [ 0.34645601  0.44323637  0.46771061 -0.38483549 -0.00774737 -0.27752091
  -0.40933575  0.15351675  0.1