In [1]:
#exercice2
import numpy as np
y=int(input("donner un nombre de ligne:"))
x=int(input("donner le nombre de la liste:"))
a=np.arange(x).reshape(y,y)
print(a)
A = np.trace(a) 
print(A)

donner un nombre de ligne:3
donner le nombre de la liste:9
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [2]:
#exercice1
from array import *
array_num = np.array([1, 9,7,9,4,9,3,0,7])
print("array 2: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

array 2: array('i', [1, 9, 7, 9, 4, 9, 3, 0, 7])
Convert the said array to an ordinary list with the same items:
[1, 9, 7, 9, 4, 9, 3, 0, 7]


In [11]:
#exercice3
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=int(input("give a number"))
for i in a:
    for j in i:
        if j>b:
            
            print(j)

give a number5
6
7
8
9
9


In [7]:
#exercice4
import numpy as np
a=np.random.randint(2,10,size=(2,2))
b=np.random.randint(2,10,size=(2,2))
print(a)
print(b)
c=a+b
print(c)

[[8 9]
 [4 5]]
[[4 8]
 [2 3]]
[[12 17]
 [ 6  8]]


In [7]:
#exercice5
import numpy as np
print("Original matrix:\n")
X = np.random.randint(5, 10,(2,2))
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=0, keepdims=True)
print(Y)



Original matrix:

[[8 9]
 [5 5]]

Subtract the mean of each row of the said matrix:

[[ 1.5  2. ]
 [-1.5 -2. ]]
